[[subreddits]]
name = "learnprogramming"

[[subreddits]]
name = "gamedev"

[[subreddits]]
name = "coding"

[[subreddits]]
name = "engineering"

[[subreddits]]
name = "askengineers"

[[subreddits]]
name = "compsci"

[[subreddits]]
name = "music"

[[subreddits]]
name = "golang"

[[subreddits]]
name = "softwarearchitecture"

[[subreddits]]
name = "DomainDrivenDesign"

[[subreddits]]
name = "WeAreTheMusicMakers"

[[subreddits]]
name = "guitarlessons"

[[subreddits]]
name = "spotify"

[[subreddits]]
name = "ableton"

[[subreddits]]
name = "hiphopheads"

[[subreddits]]
name = "hiphopimages"

[[subreddits]]
name = "guitar"